# Generated by Django 5.1.3 on 2024-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('job_profile', models.TextField()),
                ('date_of_drive', models.DateField()),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sslc_percent', models.FloatField()),
                ('sslc_year', models.IntegerField()),
                ('hsc_percent', models.FloatField()),
                ('hsc_year', models.IntegerField()),
                ('ug_percent', models.FloatField()),
                ('ug_year', models.IntegerField()),
                ('skills', models.TextField()),
                ('resume_link', models.URLField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
