# Generated by Django 5.1.3 on 2024-12-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='company_name',
        ),
        migrations.AddField(
            model_name='placement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recApp.company'),
        ),
    ]
