# Generated by Django 5.1.3 on 2025-01-02 05:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0003_studentprofile_department_studentprofile_pg_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('sslc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sslc_year', models.IntegerField(blank=True, null=True)),
                ('hsc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hsc_year', models.IntegerField(blank=True, null=True)),
                ('ug_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ug_year', models.IntegerField(blank=True, null=True)),
                ('pg_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pg_year', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
