# Generated by Django 5.1.3 on 2025-01-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
