# Generated by Django 5.1.3 on 2025-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0007_notification_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
