# Generated by Django 5.1.3 on 2025-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0008_placement_last_date_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='date_of_drive',
            field=models.DateField(blank=True, null=True),
        ),
    ]
