# Generated by Django 5.1.3 on 2025-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0012_alter_student_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placedstudent',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MMH', 'MMH'), ('MSW', 'MSW'), ('BBA', 'BBA'), ('B.COM', 'B.COM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MMH', 'MMH'), ('MSW', 'MSW'), ('BBA', 'BBA'), ('B.COM', 'B.COM')], max_length=100),
        ),
    ]
