# Generated by Django 5.1.3 on 2025-02-03 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0014_remove_student_is_placed_alter_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Academic year must be in the format 'YYYY-YY'.", regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
