# Generated by Django 5.1.3 on 2025-02-03 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0015_alter_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid academic year range, e.g., 2023-2025', regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
