# Generated by Django 5.1.3 on 2025-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0016_student_is_placed_alter_student_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street',
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
