# Generated by Django 5.1.3 on 2025-02-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0018_remove_placement_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='job_profile',
            new_name='job_description',
        ),
    ]
