# Generated by Django 5.1.3 on 2025-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0019_rename_job_profile_placement_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='placement_type',
            field=models.CharField(default='Offline', max_length=50),
        ),
    ]
