# Generated by Django 5.1.3 on 2025-02-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0020_placement_placement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='placement_type',
            new_name='recruitment_type',
        ),
    ]
