# Generated by Django 5.1.3 on 2025-02-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0021_rename_placement_type_placement_recruitment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedstudent',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='name',
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recApp.student'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='date_of_drive',
            field=models.DateField(blank=True, null=True, verbose_name='Drive Date'),
        ),
    ]
