# Generated by Django 5.1.3 on 2025-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0022_remove_placedstudent_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedstudent',
            name='student',
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='department',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MMH', 'MMH'), ('MSW', 'MSW'), ('BBA', 'BBA'), ('B.COM', 'B.COM')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name'),
        ),
    ]
