# Generated by Django 5.1.3 on 2025-02-19 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0023_remove_placedstudent_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MMH', 'MMH'), ('MSW', 'MSW'), ('BBA', 'BBA'), ('B.COM', 'B.COM')], max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('placed_year', models.IntegerField()),
                ('offer_letter', models.FileField(upload_to='offer_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
